"""Qt-free musical selection and debug-output services."""

from synesthesia_machine.midi.debug_synth import (
    DebugSynth,
    DebugSynthFactory,
    DebugSynthService,
    NullDebugSynth,
    SynthConfiguration,
    SynthWaveform,
    enumerate_audio_output_devices,
)
from synesthesia_machine.midi.output_service import (
    MidiMessage,
    MidiMessageType,
    MidiOutputBackend,
    MidiOutputConfiguration,
    MidiOutputPort,
    MidiOutputService,
    MidiOutputServiceFactory,
    MidiOutputServiceProtocol,
    MidiPortUnavailableError,
    MidiServiceStatus,
    MidoRtMidiBackend,
    MockMidiOutputBackend,
    MockMidiOutputPort,
    NullMidiOutputService,
    VelocityUpdatePolicy,
    enumerate_midi_output_devices,
)
from synesthesia_machine.midi.scales import (
    BUILTIN_SCALE_REGISTRY,
    CUSTOM_SCALE_ID,
    PITCH_CLASS_NAMES,
    MusicalSelector,
    ScaleDefinition,
    ScaleRegistry,
    parse_custom_pitch_class_mask,
    resolve_musical_selector,
    select_midi_notes,
)
from synesthesia_machine.midi.smf import (
    MidiExportEvent,
    encode_standard_midi_file,
)

__all__ = [
    "BUILTIN_SCALE_REGISTRY",
    "CUSTOM_SCALE_ID",
    "PITCH_CLASS_NAMES",
    "DebugSynth",
    "DebugSynthFactory",
    "DebugSynthService",
    "MidiExportEvent",
    "MidiMessage",
    "MidiMessageType",
    "MidiOutputBackend",
    "MidiOutputConfiguration",
    "MidiOutputPort",
    "MidiOutputService",
    "MidiOutputServiceFactory",
    "MidiOutputServiceProtocol",
    "MidiPortUnavailableError",
    "MidiServiceStatus",
    "MidoRtMidiBackend",
    "MockMidiOutputBackend",
    "MockMidiOutputPort",
    "MusicalSelector",
    "NullDebugSynth",
    "NullMidiOutputService",
    "ScaleDefinition",
    "ScaleRegistry",
    "SynthConfiguration",
    "SynthWaveform",
    "VelocityUpdatePolicy",
    "encode_standard_midi_file",
    "enumerate_audio_output_devices",
    "enumerate_midi_output_devices",
    "parse_custom_pitch_class_mask",
    "resolve_musical_selector",
    "select_midi_notes",
]
