"""Public schema-versioned graph persistence facade."""

from synesthesia_machine.persistence.clipboard import (
    CLIPBOARD_FRAGMENT_VERSION,
    ClipboardFragment,
    copy_fragment,
    fragment_from_json,
    fragment_to_json,
    remap_fragment,
)
from synesthesia_machine.persistence.graph_io import (
    GraphPersistenceError,
    graph_from_data,
    graph_from_json,
    graph_to_data,
    graph_to_json,
    load_graph,
    save_graph,
)
from synesthesia_machine.persistence.media_relink import (
    MEDIA_ABSOLUTE_FALLBACK_KEY,
    MEDIA_FINGERPRINT_KEY,
    MEDIA_SIZE_KEY,
    MissingMediaReference,
    RelinkMatch,
    RelinkVerification,
    find_missing_media,
    media_fingerprint,
    verify_relink_candidate,
)
from synesthesia_machine.persistence.schemas import (
    GRAPH_SCHEMA_VERSION,
    ConnectionSchemaV1,
    GraphSchemaV1,
    GroupSchemaV1,
    JsonObject,
    JsonValue,
    NodeSchemaV1,
    migrate_graph_data,
    migrate_v0_to_v1,
)

__all__ = [
    "CLIPBOARD_FRAGMENT_VERSION",
    "GRAPH_SCHEMA_VERSION",
    "MEDIA_ABSOLUTE_FALLBACK_KEY",
    "MEDIA_FINGERPRINT_KEY",
    "MEDIA_SIZE_KEY",
    "ClipboardFragment",
    "ConnectionSchemaV1",
    "GraphPersistenceError",
    "GraphSchemaV1",
    "GroupSchemaV1",
    "JsonObject",
    "JsonValue",
    "MissingMediaReference",
    "NodeSchemaV1",
    "RelinkMatch",
    "RelinkVerification",
    "copy_fragment",
    "find_missing_media",
    "fragment_from_json",
    "fragment_to_json",
    "graph_from_data",
    "graph_from_json",
    "graph_to_data",
    "graph_to_json",
    "load_graph",
    "media_fingerprint",
    "migrate_graph_data",
    "migrate_v0_to_v1",
    "remap_fragment",
    "save_graph",
    "verify_relink_candidate",
]
