"""Image/channel-to-musical-state node definitions."""

from synesthesia_machine.nodes import NodeDefinition
from synesthesia_machine.nodes.synesthesia.channel_to_pitch import (
    CHANNEL_TO_PITCH_TYPE_ID,
    ChannelToPitchRuntime,
    channel_histogram_to_midi_state,
)
from synesthesia_machine.nodes.synesthesia.channel_to_pitch import (
    create_synesthesia_definitions as create_channel_to_pitch_definitions,
)
from synesthesia_machine.nodes.synesthesia.edges_to_pitch import (
    AREA,
    CENTROID_X,
    CENTROID_Y,
    CIRCULARITY,
    EDGE_STRENGTH,
    EDGES_TO_PITCH_TYPE_ID,
    EXTERNAL,
    ORIENTATION,
    PERIMETER,
    TREE,
    ContourFeatures,
    EdgesToPitchRuntime,
    create_edges_to_pitch_definitions,
    edges_to_midi_state,
    extract_contour_features,
)
from synesthesia_machine.nodes.synesthesia.fourier import (
    BAND_MEAN,
    BAND_PERCENTILE,
    FOURIER_TYPE_ID,
    HAMMING,
    HANN,
    HORIZONTAL,
    NONE,
    RADIAL_MAGNITUDE,
    VERTICAL,
    FourierBandMapKey,
    FourierRuntime,
    FourierShapeCache,
    build_fourier_band_map,
    create_fourier_definitions,
    fourier_band_amplitudes,
    fourier_to_midi_state,
)
from synesthesia_machine.nodes.synesthesia.musical import (
    COMMON_MUSICAL_PARAMETER_GROUP,
    COMMON_MUSICAL_PARAMETER_IDS,
    CommonMusicalSettings,
    common_musical_parameter_specs,
    midi_state_from_candidates,
    resolve_common_musical_settings,
    validate_common_musical_parameters,
)
from synesthesia_machine.nodes.synesthesia.optical_flow import (
    ACCURATE,
    BALANCED,
    CELL_NOTES,
    DIRECTION,
    FARNEBACK_PRESETS,
    FAST,
    GLOBAL_HISTOGRAM,
    HORIZONTAL_POSITION,
    MAGNITUDE,
    MAXIMUM_MAGNITUDE,
    MEAN_MAGNITUDE,
    MOVING_PIXEL_FRACTION,
    OPTICAL_FLOW_TYPE_ID,
    VERTICAL_POSITION,
    FarnebackPreset,
    FlowCell,
    OpticalFlowRuntime,
    calculate_dense_flow,
    create_optical_flow_definitions,
    extract_flow_cells,
    flow_to_midi_state,
    optical_flow_to_midi_state,
)
from synesthesia_machine.nodes.synesthesia.scanline import (
    BOTTOM_TO_TOP,
    MAXIMUM,
    MEAN,
    PING_PONG,
    SCANLINE_TYPE_ID,
    TOP_TO_BOTTOM,
    ScanlineRuntime,
    create_scanline_definitions,
    scanline_to_midi_state,
)


def create_synesthesia_definitions() -> tuple[NodeDefinition, ...]:
    """Return the current ordered visual-to-musical node catalogue."""

    return (
        *create_channel_to_pitch_definitions(),
        *create_scanline_definitions(),
        *create_edges_to_pitch_definitions(),
        *create_fourier_definitions(),
        *create_optical_flow_definitions(),
    )


__all__ = [
    "ACCURATE",
    "AREA",
    "BALANCED",
    "BAND_MEAN",
    "BAND_PERCENTILE",
    "BOTTOM_TO_TOP",
    "CELL_NOTES",
    "CENTROID_X",
    "CENTROID_Y",
    "CHANNEL_TO_PITCH_TYPE_ID",
    "CIRCULARITY",
    "COMMON_MUSICAL_PARAMETER_GROUP",
    "COMMON_MUSICAL_PARAMETER_IDS",
    "DIRECTION",
    "EDGES_TO_PITCH_TYPE_ID",
    "EDGE_STRENGTH",
    "EXTERNAL",
    "FARNEBACK_PRESETS",
    "FAST",
    "FOURIER_TYPE_ID",
    "GLOBAL_HISTOGRAM",
    "HAMMING",
    "HANN",
    "HORIZONTAL",
    "HORIZONTAL_POSITION",
    "MAGNITUDE",
    "MAXIMUM",
    "MAXIMUM_MAGNITUDE",
    "MEAN",
    "MEAN_MAGNITUDE",
    "MOVING_PIXEL_FRACTION",
    "NONE",
    "OPTICAL_FLOW_TYPE_ID",
    "ORIENTATION",
    "PERIMETER",
    "PING_PONG",
    "RADIAL_MAGNITUDE",
    "SCANLINE_TYPE_ID",
    "TOP_TO_BOTTOM",
    "TREE",
    "VERTICAL",
    "VERTICAL_POSITION",
    "ChannelToPitchRuntime",
    "CommonMusicalSettings",
    "ContourFeatures",
    "EdgesToPitchRuntime",
    "FarnebackPreset",
    "FlowCell",
    "FourierBandMapKey",
    "FourierRuntime",
    "FourierShapeCache",
    "OpticalFlowRuntime",
    "ScanlineRuntime",
    "build_fourier_band_map",
    "calculate_dense_flow",
    "channel_histogram_to_midi_state",
    "common_musical_parameter_specs",
    "create_edges_to_pitch_definitions",
    "create_fourier_definitions",
    "create_optical_flow_definitions",
    "create_scanline_definitions",
    "create_synesthesia_definitions",
    "edges_to_midi_state",
    "extract_contour_features",
    "extract_flow_cells",
    "flow_to_midi_state",
    "fourier_band_amplitudes",
    "fourier_to_midi_state",
    "midi_state_from_candidates",
    "optical_flow_to_midi_state",
    "resolve_common_musical_settings",
    "scanline_to_midi_state",
    "validate_common_musical_parameters",
]
